const doeState={lowTemp:110,highTemp:130,lowTime:1.5,highTime:2.5,runs:null};
const doeText=(en,zh)=>t(en,zh);
function doeNum(n){return new Intl.NumberFormat(lang==='zh'?'zh-CN':lang==='fr'?'fr-FR':'en-US',{maximumFractionDigits:3}).format(n)}
function doeBounds(){const ids=['lowTemp','highTemp','lowTime','highTime'];const values=ids.map(id=>{const raw=document.getElementById('doe-'+id).value;return raw.trim()===''?NaN:Number(raw)});if(values.some(v=>!Number.isFinite(v))||values[0]>=values[1]||values[2]>=values[3])return null;return Object.fromEntries(ids.map((id,i)=>[id,values[i]]))}
function doePoints(bounds){const {lowTemp:lT,highTemp:hT,lowTime:lS,highTime:hS}=bounds;return [{temp:lT,time:lS,kind:'corner'},{temp:hT,time:lS,kind:'corner'},{temp:lT,time:hS,kind:'corner'},{temp:hT,time:hS,kind:'corner'},...Array.from({length:3},()=>({temp:(lT+hT)/2,time:(lS+hS)/2,kind:'center'}))]}
function doeChart(bounds){const p=doePoints(bounds),xl=94,xh=446,yt=40,yb=260;const dots=p.slice(0,4).map((v,i)=>`<g class="doe-point"><circle cx="${i%2?xh:xl}" cy="${i<2?yb:yt}" r="8"/><text x="${i%2?xh-19:xl+16}" y="${i<2?yb-13:yt+27}">${doeNum(v.temp)} / ${doeNum(v.time)}</text></g>`).join('');return `<svg class="doe-chart" viewBox="0 0 540 330" role="img" aria-label="${doeText('Four corner runs and three repeated center points','四个角点与三个重复中心点')}"><rect x="94" y="40" width="352" height="220" rx="12"/><path d="M94 260V40H446 M94 260H446"/><path class="doe-cross" d="M270 40V260 M94 150H446"/>${dots}<circle class="doe-center" cx="270" cy="150" r="14"/><text class="doe-center-label" x="290" y="156">${doeText('Center × 3','中心点 × 3')}</text><text class="doe-axis" x="270" y="313" text-anchor="middle">${doeText('Temperature (°C)','温度 (°C)')}</text><text class="doe-axis" x="15" y="154" transform="rotate(-90 15 154)" text-anchor="middle">${doeText('Sealing time (s)','热封时间 (s)')}</text></svg>`}
function doeTable(){if(!doeState.runs)return '';return `<div class="doe-table"><h5>${doeText('Randomized run order','随机实验顺序')}</h5><div class="table-wrap"><table><thead><tr><th>${doeText('Run','顺序')}</th><th>${doeText('Temperature (°C)','温度 (°C)')}</th><th>${doeText('Sealing time (s)','热封时间 (s)')}</th><th>${doeText('Point','实验点')}</th></tr></thead><tbody>${doeState.runs.map((r,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${doeNum(r.temp)}</td><td>${doeNum(r.time)}</td><td>${r.kind==='center'?doeText('Center','中心点'):doeText('Corner','角点')}</td></tr>`).join('')}</tbody></table></div></div>`}
function doePanel(){return `<section class="doe-panel" aria-labelledby="doe-heading"><div class="doe-header"><div><span class="kicker">${doeText('OQ / EXPERIMENT PLAN','OQ / 实验设计')}</span><h4 id="doe-heading">${doeText('Temperature × sealing time','温度 × 热封时间')}</h4></div><span class="doe-design">2² + 3 ${doeText('center points','个中心点')}</span></div><p>${doeText('Explore the proposed bounds, then use the experimental runs to assess seal quality and define the operating window.','设定候选范围，用实验点比较封口质量，再确定工艺窗口。')}</p><div class="doe-fields"><fieldset><legend>${doeText('Temperature (°C)','温度 (°C)')}</legend><label>${doeText('Lower','下限')}<input id="doe-lowTemp" type="number" inputmode="decimal" step="any" value="${doeState.lowTemp}" oninput="updateDOE()"></label><label>${doeText('Upper','上限')}<input id="doe-highTemp" type="number" inputmode="decimal" step="any" value="${doeState.highTemp}" oninput="updateDOE()"></label></fieldset><fieldset><legend>${doeText('Sealing time (s)','热封时间 (s)')}</legend><label>${doeText('Lower','下限')}<input id="doe-lowTime" type="number" inputmode="decimal" step="any" value="${doeState.lowTime}" oninput="updateDOE()"></label><label>${doeText('Upper','上限')}<input id="doe-highTime" type="number" inputmode="decimal" step="any" value="${doeState.highTime}" oninput="updateDOE()"></label></fieldset></div><p class="doe-error" id="doe-error" role="status" hidden>${doeText('Enter valid bounds with each lower limit below its upper limit.','请输入有效上下限，且下限须小于上限。')}</p><div id="doe-plot">${doeChart(doeState)}</div><div class="doe-actions"><span>${doeText('Four corners · three center repeats','四个角点 · 三次中心点重复')}</span><button class="primary" type="button" onclick="generateDOERuns()">${doeText('Generate Runs','生成实验表')}</button></div><div id="doe-runs" aria-live="polite">${doeTable()}</div></section>`}
function updateDOE(){const b=doeBounds(),error=document.getElementById('doe-error');error.hidden=!!b;document.querySelector('.doe-actions button').disabled=!b;if(!b)return;Object.assign(doeState,b);doeState.runs=null;document.getElementById('doe-plot').innerHTML=doeChart(b);document.getElementById('doe-runs').innerHTML=''}
function generateDOERuns(){const b=doeBounds();if(!b)return;Object.assign(doeState,b);const runs=doePoints(b);for(let i=runs.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[runs[i],runs[j]]=[runs[j],runs[i]]}doeState.runs=runs;document.getElementById('doe-runs').innerHTML=doeTable()}
async function copyContactEmail(){const email='shengheng.cao@gmail.com';try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(email)}else{const input=document.createElement('textarea');input.value=email;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();if(!document.execCommand('copy'))throw Error('copy');input.remove()}document.getElementById('copy-status').textContent=doeText('Copied','已复制')}catch{document.getElementById('copy-status').textContent=doeText('Select the email address to copy','请选择邮箱地址复制')}}
