let latticeShape='square';
const orbit={x:-.55,y:.35,zoom:1};
function shapeNames(){return [t('Square','方格'),t('Triangle','三角'),t('Circle','圆孔')]}
function chooseLattice(s){latticeShape=s;updateSceneText()}
function latticeControls(){return `<div class="lattice-controls"><span class="kicker">${t('Pore geometry','网孔形状')}</span><div class="shape-options">${['square','triangle','circle'].map((s,i)=>`<button class="pill ${s===latticeShape?'active':''}" aria-pressed="${s===latticeShape}" onclick="chooseLattice('${s}')">${shapeNames()[i]}</button>`).join('')}</div><p>${t('Drag to rotate · Scroll or pinch to zoom','拖动旋转 · 滚轮或双指缩放')}</p><div class="view-buttons"><button onclick="orbit.zoom=Math.max(.6,orbit.zoom-.15)" aria-label="${t('Zoom out','缩小')}">−</button><button onclick="orbit.zoom=Math.min(1.7,orbit.zoom+.15)" aria-label="${t('Zoom in','放大')}">+</button><button onclick="orbit.x=-.55;orbit.y=.35;orbit.zoom=1">${t('Reset view','重置视角')}</button></div></div>`}
function bindOrbit(canvas){const points=new Map();let pinch=0;canvas.style.touchAction=scene===0?'none':'auto';canvas.onpointerdown=e=>{if(scene!==0)return;canvas.setPointerCapture(e.pointerId);points.set(e.pointerId,[e.clientX,e.clientY]);pinch=0};canvas.onpointermove=e=>{if(scene!==0||!points.has(e.pointerId))return;const old=points.get(e.pointerId);points.set(e.pointerId,[e.clientX,e.clientY]);if(points.size===1){orbit.y+=(e.clientX-old[0])*.008;orbit.x+=(e.clientY-old[1])*.008}else{const [a,b]=[...points.values()];const d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch)orbit.zoom=Math.max(.6,Math.min(1.7,orbit.zoom*d/pinch));pinch=d}};canvas.onpointerup=canvas.onpointercancel=e=>{points.delete(e.pointerId);pinch=0};canvas.addEventListener('wheel',e=>{if(scene!==0)return;e.preventDefault();orbit.zoom=Math.max(.6,Math.min(1.7,orbit.zoom*Math.exp(-e.deltaY*.001)))},{passive:false})}
function poreCells(cols,rows,size,w){const cells=[],solid=(latticeShape==='circle'?.60:.48)*(1-w/100),k=Math.sqrt(1-solid);for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const x=(i-cols/2)*size,y=(j-rows/2)*size;const a=[x,y],b=[x+size,y],c=[x+size,y+size],d=[x,y+size];const polygons=latticeShape==='triangle'?[[a,b,c],[a,c,d]]:[[a,b,c,d]];for(const outer of polygons){const cx=outer.reduce((s,p)=>s+p[0],0)/outer.length,cy=outer.reduce((s,p)=>s+p[1],0)/outer.length;let hole;if(latticeShape==='circle'){const r=Math.sqrt((1-solid)/Math.PI)*size;hole=Array.from({length:20},(_,n)=>[cx+r*Math.cos(n*Math.PI/10),cy+r*Math.sin(n*Math.PI/10)])}else hole=outer.map(([u,v])=>[cx+(u-cx)*k,cy+(v-cy)*k]);cells.push({outer,hole})}}return cells}
let meshCache={};
function renderLattice3D(ctx,w,stress,phase){const key=latticeShape+':'+w.toFixed(1);if(meshCache.key!==key)meshCache={key,cells:poreCells(10,7,55,w)};const faces=[],thick=42,ca=Math.cos(orbit.x),sa=Math.sin(orbit.x),cb=Math.cos(orbit.y),sb=Math.sin(orbit.y);function project(p,z){const x=p[0]*cb+z*sb,zz=-p[0]*sb+z*cb,y=p[1]*ca-zz*sa,depth=p[1]*sa+zz*ca;const f=1100/(1100-depth)*orbit.zoom*1.35;return [768+x*f,470+y*f,depth]}
function face(poly,z,color,hole){const pts=poly.map(p=>project(p,z));faces.push({cap:z*(ca*cb)>0?1:-1,pts,hole:hole?.map(p=>project(p,z)),depth:pts.reduce((s,p)=>s+p[2],0)/pts.length,color})}
function wall(a,b,color,z0=-thick/2,z1=thick/2){const pts=[project(a,z0),project(b,z0),project(b,z1),project(a,z1)];faces.push({pts,depth:pts.reduce((s,p)=>s+p[2],0)/4,color})}
// Two perforated skins joined by discrete posts leave open lateral passages.
const skin=3.5*(1-w/140),rim=[[-275,-192.5],[275,-192.5],[275,192.5],[-275,192.5]];
for(const z of [-thick/2,thick/2-skin]){
 for(const cell of meshCache.cells){face(cell.outer,z,'#599c93',cell.hole);face(cell.outer,z+skin,stress?'#b8d78a':'#bdebd7',cell.hole);cell.hole.forEach((a,i)=>wall(a,cell.hole[(i+1)%cell.hole.length],'#74b3a6',z,z+skin))}
 rim.forEach((a,i)=>wall(a,rim[(i+1)%4],'#79b9ac',z,z+skin));
}
const post=5.5*(1-w/110);
for(let j=0;j<=7;j++)for(let i=0;i<=10;i++){
 const x=-275+i*55,y=-192.5+j*55,x0=Math.max(-275,x-post/2),x1=Math.min(275,x+post/2),y0=Math.max(-192.5,y-post/2),y1=Math.min(192.5,y+post/2);
 const corners=[[x0,y0],[x1,y0],[x1,y1],[x0,y1]];
 corners.forEach((a,n)=>wall(a,corners[(n+1)%4],n%2?'#5c9d94':'#84c4b5',-thick/2+skin,thick/2-skin));
}
faces.sort((a,b)=>(a.cap||0)-(b.cap||0)||a.depth-b.depth);for(const f of faces){ctx.beginPath();for(const points of [f.pts,...(f.hole?[f.hole]:[])]){ctx.moveTo(points[0][0],points[0][1]);points.slice(1).forEach(p=>ctx.lineTo(p[0],p[1]));ctx.closePath()}ctx.fillStyle=f.color;ctx.fill('evenodd')}}
function drawSelectedPattern(ctx,path,spacing,lineWidth,stress){ctx.save();ctx.clip(path);const cells=poreCells(Math.ceil(1536/spacing)+2,Math.ceil(1024/spacing)+2,spacing,weight);ctx.translate(768,512);ctx.fillStyle=stress?'#c4dca0':'#b5ead5';for(const c of cells){ctx.beginPath();for(const points of [c.outer,c.hole]){ctx.moveTo(...points[0]);points.slice(1).forEach(p=>ctx.lineTo(...p));ctx.closePath()}ctx.fill('evenodd')}ctx.restore()}
